name: YaizuSample Windows CI

on: [push]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1
    - name: exec build
      env:
        GITHUBACTIONS: true
      run: |
        git clone -q --branch=master https://github.com/s-takeuchi/YaizuComLib.git ../YaizuComLib
        git checkout master
        cd build
        ./build.bat
        ./build2.bat
    - name: exec test
      env:
        GITHUBACTIONS: true
      run: |
        git clone -q --branch=master https://github.com/s-takeuchi/YaizuComLib.git ../YaizuComLib
        git checkout master
        cd build
        ./test.bat
